Feature/use newly generated catbuffer
symbol/sdk-python pull request #14
Opened 2021-12-02 23:14 UTC by gimre-xymcity

2021-12-02 23:59 UTC, Jaguar0625 requested changes

2021-12-02 23:59 UTC, Jaguar0625 commented on examples/descriptors/symbol_metadata.py
> +    value3 = b'while I pondered, weak and weary'
why this change?

2021-12-02 23:59 UTC, Jaguar0625 commented on examples/descriptors/symbol_lock.py
> +            },
would be consistent with having mosaic one line or multiple (e.g. compared to symbol_transfer.py )

2021-12-02 23:59 UTC, Jaguar0625 commented on examples/tool_utils.py
> +from binascii import unhexlify
nitpick - but really example_utils, isn't it ^^

2021-12-02 23:59 UTC, Jaguar0625 commented on examples/transaction_multisig.py
>              cosignature = (0, key_pair.public_key.bytes, key_pair.sign(transaction_hash).bytes)
should cosignature be object like mosaic? :thinking:

2021-12-02 23:59 UTC, Jaguar0625 commented on generator/test_TestVector.py
>      return cases
revert?

2021-12-02 23:59 UTC, Jaguar0625 commented on .travis.yml
> +        - git clone --depth=1 --branch=test-vectors https://github.com/symbol/catbuffer-schemas.git $CATBUFFER_SCHEMAS
why are these in catbuffer-schemas instead of test-vectors?

2021-12-02 23:59 UTC, Jaguar0625 commented on lint.sh
> -find . -type f -name "*.py" -print0 | PYTHONPATH=. xargs -0 python3 -m pylint --load-plugins pylint_quotes
revert? 😅

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/facade/SymbolFacade.py
> +        hasher.update(transaction.signature.signature)
why signature.signature? 🤔

2021-12-02 23:59 UTC, Jaguar0625 commented on tests/core/facade/test_SymbolFacade.py
> +        self.assertEqual(0x4154, transaction.type_.value)
so, before we shouldn't have been using type_ ?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +            value = value | enum_array[i]
reduce ?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +        raise ValueError('ByteArray not allowed ')
this is to catch unexpected ones?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +        # but right now symbol.yml contains als state-related objects
als => all ?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +            'Address': wrap_sdk_type(Address),
intentional to collapse Address and UnresolvedAddress?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +            'NamespaceRegistrationType': create_enum_parser('NamespaceRegistrationType'),
might be good to combine multiple dicts to avoid repetition in class names, e.g. 
```
class_name: create_enum_parser(class_name) for class_name in ['TransactionType' ...]
```

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
where is prefix coming from?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +            transaction.id = sc.MosaicId(generate_mosaic_id(address, transaction.nonce.mosaic_nonce))
i think _transaction postfix shouldn't be there based on examples ?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +        # _todo: maybe instead of doing this, there should be hint on: `namespaceRegistration.name` and `transfer.message`
probably

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +                key = 'type_'
what's this for?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +        transaction_descriptor['type'] += '_transaction'
i'm confused why you're using _transaction postfix in some places but not others?

2021-12-02 23:59 UTC, Jaguar0625 commented on tests/core/symbol/test_TransactionFactory.py
> +            Flags.ADDRESS | Flags.MOSAIC_ID | Flags.TRANSACTION_TYPE | Flags.OUTGOING | Flags.BLOCK,
👍

2021-12-02 23:59 UTC, Jaguar0625 commented on tests/core/symbol/test_TransactionFactory.py
> +            transaction.restriction_additions)
comment is wrong isn't it?

2021-12-02 23:59 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
>          default_rules = {
given that this has grown in complexity significatntly, i'd probably move it to own file and add targeted tests for it. 

otherwise, i think we need to add more tests to this class to improve coverage.

2021-12-05 15:08 UTC, Jaguar0625 commented
looks good except it seems you missed most of my earlier comments?

2021-12-13 21:01 UTC, gimre-xymcity commented on examples/descriptors/symbol_metadata.py
> +    value3 = b'while I pondered, weak and weary'
my bad, this was needed at some point (when I had str -> bytes conversion disabled),
but not needed now

2021-12-13 21:02 UTC, gimre-xymcity commented on examples/descriptors/symbol_lock.py
> +            },
wasn't sure how to format, cause three, there's array mosaic and here there's a single mosaic 🤔

2021-12-13 21:11 UTC, gimre-xymcity commented on generator/test_TestVector.py
>      return cases
no this is valid, to make it work with travis (or do you have some nicer proposal?)

2021-12-13 21:29 UTC, gimre-xymcity commented on examples/transaction_multisig.py
>              cosignature = (0, key_pair.public_key.bytes, key_pair.sign(transaction_hash).bytes)
hmm, so this example is wrong...

OLD version allowed syntactic sugar like the one, you've marked:
`cosignature = (0, key_pair.public_key.bytes, key_pair.sign(transaction_hash).bytes)`

In new version, the above should actually look like this:
```py
            cosignature = symbolchain.sc.Cosignature()
            cosignature.version = 0
            cosignature.signer_public_key = key_pair.public_key
            cosignature.signature = key_pair.sign(transaction_hash)
```

I probably could do syntactic-sugar, like we have for mosaics, but the difference here is that:
`aggregate_transaction.cosignatures.append` - is appending to already built transaction object

so if we want nicer version, I would need to add in `symbolchain.core.symbol.TransactionFactory` `.attach_cosignature`...
what do you think?

2021-12-13 21:31 UTC, gimre-xymcity commented on .travis.yml
> +        - git clone --depth=1 --branch=test-vectors https://github.com/symbol/catbuffer-schemas.git $CATBUFFER_SCHEMAS
I've asked you if I should throw vectors into schemas 😅
(it was/is in generators earlier, I _doubt_ if this should go into test-vectors repo)

2021-12-13 21:37 UTC, gimre-xymcity commented on tests/core/facade/test_SymbolFacade.py
> +        self.assertEqual(0x4154, transaction.type_.value)
technically, this itself is not a problem (i.e. we're not shadowing built-in here, but in generated code there's something like:
`type_ = TransactionType.deserialize(buffer_)`
(which without that replacement would be:
`type = TransactionType.deserialize(buffer_)`

and the letter would shadow builtin

and again, it's _local_ so even that shadow isn't super bad, but it's discouraged I think

(and yes, earlier it wasn't "nice")

2021-12-13 21:47 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
> +        raise ValueError('ByteArray not allowed ')
yes

2021-12-13 21:48 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
> +        # but right now symbol.yml contains als state-related objects
(also)

2021-12-13 22:08 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
> +            'Address': wrap_sdk_type(Address),
this is other way around, so if transaction has hint with UnresolvedAddress (say transfer tx)
first _something_ (so i.e. string will be wrapped to - SDKs Address - and then to sc.UnresolvedAddress

(obviously SDKs Address is still in place)

in case of alias transaction, hint is Address, so first "something" will be wrapped in SDKs Address and then will be passed as sc.UnresolvedAddress (via `symbol_type_converter`)

so yeah, _not_ great, but I doubt we want to distinguish the two at SDK level... (and lower level doesn't care _that_ much)

2021-12-13 22:19 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
the hint in say hash lock (body) looks like this:
```py
class HashLockTransactionBody:
    type_hints = {
        "mosaic": "struct:UnresolvedMosaic",
```

while hint for transfer tx (body), looks like this:
```py
class TransferTransactionBody:
    type_hints = {
        "recipient_address": "pod:UnresolvedAddress",
        "mosaics": "array[UnresolvedMosaic]",
```
'struct:' is skipped here, I don't remember why there's a difference, but I think it was to avoid ugly things like:
`array[enum:TransactionType]`, `array[pod:NamespaceId]` , etc.

2021-12-13 22:28 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
> +            transaction.id = sc.MosaicId(generate_mosaic_id(address, transaction.nonce.mosaic_nonce))
no this is valid,
both create() and create_embedded add:
`transaction_descriptor['type'] += '_transaction'`

that is mostly cause
`sc.EmbeddedTransactionFactory.create_by_name()` requires name with `_transaction` suffix
(and that name is obtained from actual class implementing `EmbeddedTransaction`, so would preffer _not_ to drop it on generator level... as what would be the rule)

and at the same time, I think skipping that "_transaction" part is more convenient for user

2021-12-13 22:28 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
> +        transaction_descriptor['type'] += '_transaction'
see comment above

2021-12-14 12:05 UTC, Jaguar0625 commented on examples/descriptors/symbol_lock.py
> +            },
not a big deal but, if possible, i'd try to use same formatting project wide

2021-12-14 12:05 UTC, Jaguar0625 commented on examples/transaction_multisig.py
>              cosignature = (0, key_pair.public_key.bytes, key_pair.sign(transaction_hash).bytes)
i think new version is fine

2021-12-14 12:06 UTC, Jaguar0625 commented on generator/test_TestVector.py
>      return cases
why HOME?

2021-12-14 12:10 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
> +        # _todo: maybe instead of doing this, there should be hint on: `namespaceRegistration.name` and `transfer.message`
not sure yet

2021-12-14 13:50 UTC, gimre-xymcity commented on generator/test_TestVector.py
>      return cases
easiest? (we already have `TEST_VECTORS_ROOT`, which ia also $HOME
```
env:
  global:
    RELEASE_BRANCH=main
    DEV_BRANCH=dev
    TEST_VECTORS_ROOT=$HOME/nemtech/test-vectors
    CATBUFFER_SCHEMAS=$HOME/catbuffer-schemas
```

2021-12-15 19:23 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
>          default_rules = {
take a look now

2021-12-15 19:40 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
> +                key = 'type_'
so getter/setter is actually "type_"

and inside passed descriptor, it's actually type, like here:
```py
        {
            'type': 'address_alias',
            'namespace_id': sample_namespace_id,
            'address': sample_address,
            'alias_action': 'link'
        },
```
(this is not a bug, I assume we do not expect to use "type_" in descriptors...)

above in `copy_to`, things are fine cause `['type', 'signer_public_key']` are ignored completely

here I could do `value = getattr(transaction, key, None)` below, but somehow that does not feel right
(I know there's check for invalid keys in `copy_to`, so no invalid key should reach this point anyway)

I moved the if above `all_type_hints` check though.

2021-12-15 20:38 UTC, Jaguar0625 requested changes

2021-12-15 20:38 UTC, Jaguar0625 commented on symbolchain/core/symbol/TransactionFactory.py
>  def symbol_type_converter(value):
maybe move this too?

2021-12-15 20:38 UTC, Jaguar0625 commented on symbolchain/core/symbol/ExtendedTypeParsingRules.py
> +def get_catbuffer_class(name):
could you prefix unexported funcs with underscore?

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +class TypeHintsMap(unittest.TestCase):
i think we normally postfix with Tests? 
i.e. => TypeHintsMapTests

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +            type_hints = transaction_type_hints  # pylint: disable=invalid-name
is this intended to be class property ?

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +class ExtendedTypeParsingRules(unittest.TestCase):
*Tests

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +    def test_enum_parser_can_handle_ints(self):
should you have can_handle_ints for flags too?

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +        self._assert_sdk_wrapper(b'hAAAABBBBBCCCCCDDDDDEEEE', Address('NBAUCQKBIJBEEQSCINBUGQ2DIRCEIRCEIVCUKRK'))
[minor] would use trailing comment

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +        self._assert_flags_parser([1, 2, 3, 4], [1, 2, 3, 4])
flags => enum ?

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +        self._assert_flags_parser([1, 2, 3, 4], [1, 2, 3, 4])
delete?

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +        rules = extend_type_parsing_rules(lambda value: type_breadcrumbs.append(type(value)) or value, {})
why `or value`?

2021-12-15 20:38 UTC, Jaguar0625 commented on symbolchain/core/symbol/ExtendedTypeParsingRules.py
> +        'struct:UnresolvedMosaic': create_struct_parser('UnresolvedMosaic', symbol_type_converter, base_type_parsing_rules),
would swap and put struct after wrap

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +    def test_array_parser_applies_non_array_parser(self):
non_array => non_struct?

2021-12-15 20:38 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +        self._run_rules_parser('array[UnresolvedMosaic]', input_value, expected_outcome)
i think it would improve readability to move  these above where they're used.

2021-12-16 12:35 UTC, gimre-xymcity commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +            type_hints = transaction_type_hints  # pylint: disable=invalid-name
yes, as in generated code it is...

2021-12-16 12:40 UTC, gimre-xymcity commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +    def test_enum_parser_can_handle_ints(self):
hmm, I did not realize `Flag` handles int automatically...

2021-12-16 12:53 UTC, gimre-xymcity commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +        rules = extend_type_parsing_rules(lambda value: type_breadcrumbs.append(type(value)) or value, {})
cause type converter actually needs to return a value and append is void ^^

2021-12-16 12:56 UTC, gimre-xymcity commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +    def test_array_parser_applies_non_array_parser(self):
hmm, meant that it applies "singular" parser on each element, not sure how to word it

and below `test_array_parser_applies_struct_parser` that it applies struct parser on every element

2021-12-16 13:04 UTC, Jaguar0625 commented on tests/core/symbol/test_ExtendedTypeParsingRules.py
> +            type_hints = transaction_type_hints  # pylint: disable=invalid-name
can we change generate code to uppercase?

2021-12-16 13:24 UTC, gimre-xymcity commented on symbolchain/core/symbol/TransactionFactory.py
>  def symbol_type_converter(value):
leaving as is
a) nicer to cover via TransactionFactory tests
b) extracted parts mostly deals with hints only

2021-12-16 14:46 UTC, Jaguar0625 approved these changes

2021-12-16 16:07 UTC, closed without merging

2021-12-16 16:25 UTC, gimre-xymcity commented
merged in c9352542d79c839f18ba19f970de82874e37d64c