Catbuffer generator use sdk objects
symbol/sdk-python pull request #15
Opened 2021-12-03 23:34 UTC by gimre-xymcity

generated code inside symbolchain/sc subdir as per 2d306c9dfb98dee5b7dd221595f906b8e7f275d4

2021-12-05 15:33 UTC, Jaguar0625 requested changes
isn't most of this already in symbol_catbuffer?

2021-12-05 15:33 UTC, Jaguar0625 commented on generator/PodTypeFormatter.py
> -        ]
why were these dropped?

2021-12-05 15:33 UTC, Jaguar0625 commented on symbolchain/core/BaseValue.py
> +    """Represents a base unsigned int."""
at least in cpp, some can be signed

2021-12-05 15:33 UTC, Jaguar0625 commented on symbolchain/core/BaseValue.py
> +    def __init__(self, byte_size, value, tag=None):
maybe make byte_size default to 8 ?

2021-12-05 15:33 UTC, Jaguar0625 commented on symbolchain/core/BaseValue.py
> +    def __lt__(self, other):
why lt?

2021-12-05 15:33 UTC, Jaguar0625 commented on symbolchain/core/BaseValue.py
> +        return f'0x{self.value:0{self.__byte_size * 2}X}'
probably should override __hash__

2021-12-05 15:33 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertEqual(WORD_VALUE, val.value)
feels like this _should_ be truncating

2021-12-05 15:33 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertNotEqual(val_with_explicit_tag, BaseValue(WORD_WIDTH, WORD_VALUE ^ 0xFFFFFFFF_FFFFFFFF, str))
seems redundant

2021-12-05 15:33 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        val_with_explicit_tag = BaseValue(WORD_WIDTH, WORD_VALUE - 1, str)
not sure you need explicit_tags in _this_ test aside from one case

2021-12-05 15:33 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +    def test_string_is_supported(self):
probably don't need val_with_explicit_tag in string tests either

2021-12-05 15:33 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertEqual('0xFEDCBA9876543', str(BaseValue(HALF_WORD_WIDTH, 0xFEDCBA9876543)))
isn't last one wrong?

2021-12-05 15:34 UTC, Jaguar0625 commented
also, i wonder if we should move code shared between sc and core to some _other_ directory 🤔

2021-12-06 15:26 UTC, gimre-xymcity commented on symbolchain/core/BaseValue.py
> +    def __init__(self, byte_size, value, tag=None):
a) although different, want to keep same order of args as in ByteAray
b) even then, would prefer _not_ to make it default - I mean why if it's used by generated code?

2021-12-06 15:34 UTC, gimre-xymcity commented on symbolchain/core/BaseValue.py
> +    """Represents a base unsigned int."""
I don't recall any basevalue that would be signed, is there any?

2021-12-06 15:35 UTC, gimre-xymcity commented on generator/PodTypeFormatter.py
> -        ]
lt + eq added to BaseValue, method_descriptor not needed anymore (cause access via `.value`)

2021-12-06 15:37 UTC, gimre-xymcity commented on generator/PodTypeFormatter.py
> -        ]
for arrays eq is already there (and wasn't sure if I should throw in lt), again access via (`.bytes`)

2021-12-06 15:40 UTC, gimre-xymcity commented on symbolchain/core/BaseValue.py
> +    def __lt__(self, other):
well, for things like:
`mosaics = array(Mosaic, mosaics_count, sort_key=mosaic_id)`
`keys = array(AddressKeyValue, key_value_count, sort_key=key)`

2021-12-06 15:54 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertEqual('0xFEDCBA9876543', str(BaseValue(HALF_WORD_WIDTH, 0xFEDCBA9876543)))
right now: not, cause no truncating...

2021-12-06 15:55 UTC, gimre-xymcity commented
> also, i wonder if we should move code shared between sc and core to some other directory 🤔

probably, I wasn't sure either, but we can do that easily later.

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        # wraps due to and
?

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        # positive wrap around to negative
Act + Assert: ?

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertEqual(126, BaseValue(1, 126, None, True).value)
consider swapping signed + tag

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +    def _lower_than_is_supported(self, base_value, is_signed):
lower than => less than

please :)

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +    def _lower_than_is_supported(self, base_value, is_signed):
base_value is really just (int) value, isn't it?

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertLess(untagged(130), untagged(127))
unsure what this is intended to test

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertNotEqual(BaseValue(WORD_WIDTH, WORD_VALUE, str, False), BaseValue(WORD_WIDTH, WORD_VALUE, str, True))
test name is misleading, this is passing because of tag difference

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertNotEqual(hash(BaseValue(WORD_WIDTH, WORD_VALUE // 2)), hash(BaseValue(WORD_WIDTH, WORD_VALUE // 2, None, True)))
how are these passing?

2021-12-07 12:29 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertEqual('0XFEDCBA9876543210', str(BaseValue(WORD_WIDTH, WORD_VALUE)))
can we change X => x ?

2021-12-07 18:14 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertEqual('0XFEDCBA9876543210', str(BaseValue(WORD_WIDTH, WORD_VALUE)))
not really, this is what "#" does either 0X + [A-F] or 0x + [a-f]

could ofc do it 'manually', but would rather _not_

2021-12-07 20:54 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +    def _lower_than_is_supported(self, base_value, is_signed):
bad naming, here it was supposed to mean, some kind of reference point

2021-12-07 20:56 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertLess(untagged(130), untagged(127))
perhaps this should be in some separate test

this shows how rounding works for signed base values  (using wrap-around) - that's not so obvious,
for a moment I was wondering if there should be clamping used instead...

2021-12-07 21:34 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        # positive wrap around to negative
I thought we're not doing Act + Assert on tests that are just asserts?

2021-12-07 21:35 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertEqual(126, BaseValue(1, 126, None, True).value)
a) as mentioned, wanted same order as in ByteArray
b) no need - in generated code all types will have tag...

2021-12-07 21:36 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertLess(untagged(130), untagged(127))
nevermind, this is already covered in "_caps_" test, so pretty much senseless here

2021-12-07 21:43 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertNotEqual(BaseValue(WORD_WIDTH, WORD_VALUE, str, False), BaseValue(WORD_WIDTH, WORD_VALUE, str, True))
hopefully better

2021-12-07 21:55 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertNotEqual(hash(BaseValue(WORD_WIDTH, WORD_VALUE // 2)), hash(BaseValue(WORD_WIDTH, WORD_VALUE // 2, None, True)))
1st is signed vs unsigned.
2nd as well

although technically hash CAN be same if VALUES are not equal, I think I'd rather avoid it.

used descriptors, hopefully bit better now, could throw in few newlines

2021-12-07 23:01 UTC, Jaguar0625 commented on tests/core/test_ByteArray.py
>          self.assertNotEqual(byte_array, None)
add not equal test?

2021-12-07 23:01 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
>      def test_equality_is_supported_different_signedness(self):
seems quite complicated, maybe we need different signed unsigned types to simplify? 🤔

2021-12-08 20:04 UTC, gimre-xymcity commented on tests/test/OrderTestUtils.py
> +    def __operator_helper(self, descriptor, values, operation, assert_equality=False):
poor naming, it's not really testing equality this helper is used to test:
 * `assert_equality = False: <, >`
 * `assert_equality = True: <=, >=`

2021-12-08 21:55 UTC, gimre-xymcity commented on tests/test/OrderTestUtils.py
> +            _ = operation(val_untagged < None)
NotImplemented results in this (I think it's correct)

2021-12-08 23:18 UTC, gimre-xymcity commented on tests/core/test_ByteArray.py
>          self.assertNotEqual(byte_array, None)
this was actually bit trickier, assertNotEqual was already testing it (unintended)
so to solve this, I've redone tests, and now they are doing it like:
`self.assertTrue(operator.eq(a, b))`

or `self.assertFalse(operator.ne(a, b))`

this is hidden inside `equality_is_supported` and `inequality_is_supported`

2021-12-08 23:19 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +    )
a) python doesn't care (much ^^)
b) linters do not care
c) future diffs usually are bit nicer 😁 (altering less lines)

2021-12-09 01:25 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        # positive wrap around to negative
well, you have comment anyway, so it usually has some prefix  😅

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertEqual(0xCDEF0123, val.value)
consider testing DEFAULT_VALUE != val.value

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertEqual(0x7FFF, BaseValue(2, 32767).value)
maybe Sanity - since this one is not wrapping

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        # Arrange:
drop arrange? (x2)

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.inequality_is_supported(descriptor, DEFAULT_VALUE)
minor: you could refactor as only difference is DESCRIPTOR_UNSIGNED vs DESCRIPTOR_SIGNED

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.less_than_is_supported(self.DESCRIPTOR_UNSIGNED, ORDER_TESTS_MAX_UNSIGNED)
can you remind me why one of these isn't sufficient for unsigned?

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +    def test_less_or_equal_is_supported_unsigned(self):
[minor] it's usually 

less **than** or equal
greater **than** or equal

you can rename or not

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_BaseValue.py
> +        self.assertGreaterEqual(self.DESCRIPTOR_SIGNED.untagged(5), self.DESCRIPTOR_SIGNED.untagged(-3))
minor: i might move these into previous functions

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/core/test_ByteArray.py
> +from tests.core.test_BaseValue import DEFAULT_VALUE
would try to avoid links between test classes. is this stale as DEFAULT_VALUE is defined below anyway. 🤔

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +    def __equality_helper_tag_independent(factory, descriptor, value, checks):
i think we've generally been using single _ for privates? any reason to use double here?

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +        checks = [
not sure if you need local vs
```py
        self.__equality_helper(descriptor, value, [
            lambda a, b: self.assertTrue(operator.eq(a, b)),
            lambda a, b: self.assertFalse(operator.eq(a, b)),
        ])

```

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +        self.__order_helper(descriptor, ordered_values, operator.le)
shouldn't you be passing True here and in gte overload?

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +        self.__order_helper(descriptor, ordered_values, operator.ge)
swap operators to match function names ;)

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +        val_tagged = descriptor.tagged(values[2])
i think this would be easier to read if you have only one local (value) and create tagged val inline in one assert where it's used

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +        self.assertFalse(operation(val_untagged, descriptor.untagged(values[0])))
for symmetry, i guess you'd want False(descriptor.untagged(values[2]), val_untagged)

2021-12-09 01:53 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +            _ = operation(val_untagged < None)
what is raising exception(s)?

2021-12-09 01:55 UTC, Jaguar0625 commented on tests/test/ComparisonTestUtils.py
> +        if assert_equality:
you should have else that does assertFalse too

2021-12-09 12:21 UTC, gimre-xymcity commented on tests/test/OrderTestUtils.py
> +            _ = operation(val_untagged < None)
https://github.com/python/cpython/blob/8319114feedd2a5b77378bba24eb9fb2689c5033/Objects/object.c#L717

2021-12-09 13:45 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertEqual(0x7FFF, BaseValue(2, 32767).value)
hmm, it was supposed to show that both BaseValues end up having same `.value`

2021-12-09 13:49 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.less_than_is_supported(self.DESCRIPTOR_UNSIGNED, ORDER_TESTS_MAX_UNSIGNED)
technically it is, but wasn't sure if this should show that it works at the end of the range or not (i.e, doesn't do anything weird when high-bit is set)

2021-12-09 13:51 UTC, gimre-xymcity commented on tests/core/test_BaseValue.py
> +        self.assertGreaterEqual(self.DESCRIPTOR_SIGNED.untagged(5), self.DESCRIPTOR_SIGNED.untagged(-3))
hm?

2021-12-09 13:54 UTC, gimre-xymcity commented on tests/core/test_ByteArray.py
> +from tests.core.test_BaseValue import DEFAULT_VALUE
aw gawd, IDK where did this came from o0

2021-12-09 13:59 UTC, gimre-xymcity commented on tests/test/ComparisonTestUtils.py
> +    def __equality_helper_tag_independent(factory, descriptor, value, checks):
in general: _ is usually for "protected", __ is for privates, 

but I forgot this class is not inherited, so _ will be fine here

2021-12-09 14:03 UTC, gimre-xymcity commented on tests/test/ComparisonTestUtils.py
> +        self.__order_helper(descriptor, ordered_values, operator.le)
it's `le`, but you're right True was missing 😬

2021-12-09 15:36 UTC, gimre-xymcity commented
merged into `feature/sdk-v3`

2021-12-09 15:36 UTC, closed without merging